### ISSUE TITLE
Issue with pytest connection to API server

### ISSUE THREAD

**Issue by bennathill** [automationhacks/people-api#9]
Hi,
I am able to run the server successfully after
`python server.py`

But when I go to run the first test against the API (test_read_all_has_kent()), I am receiving the HTTPConnection error below that I am unable to resolve.

`self = <urllib3.connection.HTTPConnection object at 0x000002240F35E4F0>

    def _new_conn(self):
        """Establish a socket connection and set nodelay settings on it.
    
        :return: New socket connection.
        """
        extra_kw = {}
        if self.source_address:
            extra_kw["source_address"] = self.source_address
    
        if self.socket_options:
            extra_kw["socket_options"] = self.socket_options
    
        try:
                conn = connection.create_connection(
                (self._dns_host, self.port), self.timeout, **extra_kw
            )`

..\venv2\lib\site-packages\urllib3\connection.py:169:

This also occurs of any other tests I try to run with pytest.

**Comment by pulkit-rajpal** [comment]
yes, Same for me as well getting the above-mentioned error @automationhacks  if possible please share the fix for above !
Thanks

**Comment by pulkit-rajpal** [comment]
Hi, So I have got the Issue BASE_URI which is defined in the config class as http://0.0.0.0:5000/api/people while it works in postman requests lib didn't recognize or have an issue with it! So the fix is to use http://127.0.0.1:5000/api/people instead of the previous one!

**Comment by automationhacks** [comment]
Hi @bennathill, Are you still facing the same issue?

So whenever you are getting a connection error, the first thing to check is whether the API is up? Before running the test ensure you have started the server from people-api, also in case you have used a different port to start the service on then the `BASE_URI` is updated accordingly.

```
BASE_URI = 'http://0.0.0.0:5001/api/people'
```

You could do what Pulkit has suggested as well. I'll close the issue but feel free to reopen in case its not fixed.
